LIDRCIRCLE = 0
LIDRRECTANGLE = 1

LIDRBUFFER = 1
LIDRBOTTOMBUFFER = 1
LIDRLEFTBUFFER = 2
LIDRTOPBUFFER = 3
LIDRRIGHTBUFFER = 4

LASNONCLASSIFIED = 0
LASUNCLASSIFIED = 1
LASGROUND = 2
LASLOWVEGETATION = 3
LASMEDIUMVEGETATION = 4
LASHIGHVEGETATION = 5
LASBUILDING = 6
LASLOWPOINT = 7
LASKEYPOINT = 8
LASWATER = 9
LASFIELDS = c("X", "Y", "Z", "Intensity", "ReturnNumber", "NumberOfReturns", "ScanDirectionFlag", "EdgeOfFlightline", "Classification", "ScanAngle", "UserData", "gpstime", "PointSourceID", "R", "G", "B")
