# ===============================================================================
#
# PROGRAMMERS:
#
# jean-romain.roussel.1@ulaval.ca  -  https://github.com/Jean-Romain/lidR
#
# COPYRIGHT:
#
# Copyright 2016-2018 Jean-Romain Roussel
#
# This file is part of lidR R package.
#
# lidR is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ===============================================================================

#' Summary and Print for \code{LAS*} object
#'
#' @param object,x A \code{LAS*} object
#' @param ... Unused
#'
#' @return NULL, used for its side effect of printing informations
setGeneric("print", function(x, ...)
  standardGeneric("print"))

setGeneric("summary", function(object, ...)
  standardGeneric("summary"))

#' Plot a LAS* object
#'
#' Plot displays a 3D interactive windows based on rgl for \link{LAS} objects
#'
#' @param x A \code{LAS*} object
#' @param y Unused (inherited from R base)
#' @param color characters. The attribute used to color the point cloud. Default is Z coordinates. RGB
#' is an allowed string even if it refers to three attributes at a time.
#' @param colorPalette characters. A vector of colors such as that generated by heat.colors,
#' topo.colors, terrain.colors or similar functions. Default is \code{height.colors(50)}
#' provided by the package \code{lidR}
#' @param bg The color for the background. Default is black.
#' @param trim numeric. Enables trimming of values when outliers break the color palette range.
#' Every point with a value higher than \code{trim} will be plotted with the highest color.
#' @param clear_artifact logical. It is a known and docunented issue that the 3D visialisation with
#' \code{rgl} displays artifacts. The points look aligned and/or regularly space in some view angle.
#' This is because \code{rgl} computes with single precsion \code{float}. To fix that the user can
#' set this option to \code{TRUE}. In this case the point cloud is shifted to (0,0) to reduce the
#' number of digit needed to represent its coordinates. The drawback is that the user cannot anymore
#' add other object in the scene since de coordinates will not match anymore.
#' @param nbits integer. If \code{color = RGB} it assume that RGB color are coded on 16 bits as described
#' in the LAS format specifications. Actually this is not always respected. If the colors are stored
#' on 8 bits set this parameter to 8.
#' @param backend character. Can be \code{"rgl"} or \code{"pcv"}. If \code{"rgl"} is chosen
#' the display relies on the \code{rgl} package. If \code{"pcv"} is chosen it relies on the
#' \code{PointCloudViewer} package which is much more efficient and can handle million of points
#' using few memory. \code{PointCloudViewer} is not available on CRAN yet and should
#' be install from github (see. \url{https://github.com/Jean-Romain/PointCloudViewer}).
#' @param ... Will be passed to \link[rgl:points3d]{points3d} (LAS) or \link[graphics:plot]{plot}
#' if \code{mapview = FALSE} or to \link[mapview:mapView]{mapview} if \code{mapview = TRUE} (LAScatalog).
#' @examples
#' LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
#' las <- readLAS(LASfile)
#'
#' plot(las, clear_artifact = TRUE)
#'
#' # Outliers in intensity breaks the color range. Use the trim parameter.
#' col <- heat.colors(50)
#' plot(las, color = Intensity, colorPalette = col, clear_artifact = TRUE)
#' plot(las, color = Intensity, colorPalette = col, trim = 70, clear_artifact = TRUE)
#' @export
#' @method plot LAS
setGeneric("plot", function(x, y, ...)
  standardGeneric("plot"))

#' Test if a \code{LAS} object is empty
#'
#' An empty \code{LAS} object is a point cloud with 0 points
#'
#' @param object A \code{LAS} object
#' @param ... Unused
#'
#' @return TRUE or FALSE
#'
#' @examples
#' LASfile <- system.file("extdata", "example.laz", package="rlas")
#' las = readLAS(LASfile)
#' is.empty(las)
#'
#' las = new("LAS")
#' is.empty(las)
#' @export
setGeneric("is.empty", function(object, ...)
  standardGeneric("is.empty"))

#' Surface covered by a LAS* object.
#'
#' Surface covered by a \code{LAS*} object. For \code{LAS} point cloud it is computed based on the
#' convex hull of the points. For a \code{LAScatalog} it is computed a the sum of the bounding box
#' of the files. For overlaping tiles the value may be larger that the total covered area because
#' some regions are sampled twice.
#'
#' @param x An object of the class \code{LAS*}
#' @param ... unused
#'
#' @return numeric. The area of the object computed in the same units as the coordinate reference system
#' @export
#' @importMethodsFrom raster area
#' @rdname area
setGeneric("area", function(x, ...)
  standardGeneric("area"))