# ===============================================================================
#
# PROGRAMMERS:
#
# jean-romain.roussel.1@ulaval.ca  -  https://github.com/Jean-Romain/lidR
#
# COPYRIGHT:
#
# Copyright 2016-2018 Jean-Romain Roussel
#
# This file is part of lidR R package.
#
# lidR is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
# ===============================================================================

#' Summary and Print for \code{LAS*} objects
#'
#' @param object,x A \code{LAS*} object
#' @param ... Unused
#'
#' @return NULL, used for its side-effect of printing information
setGeneric("print", function(x, ...)
  standardGeneric("print"))

setGeneric("summary", function(object, ...)
  standardGeneric("summary"))

#' Plot a LAS* object
#'
#' Plot displays a 3D interactive windows-based on rgl for \link{LAS} objects
#'
#' @param x A \code{LAS*} object
#' @param y Unused (inherited from R base)
#' @param color characters. The attribute used to color the point cloud. Default is Z coordinates. RGB
#' is an allowed string even if it refers to three attributes simultaneously.
#' @param colorPalette characters. A vector of colors such as that generated by heat.colors,
#' topo.colors, terrain.colors or similar functions. Default is \code{height.colors(50)}
#' provided by the package \code{lidR}
#' @param bg The color for the background. Default is black.
#' @param trim numeric. Enables trimming of values when outliers break the color palette range.
#' Every point with a value higher than \code{trim} will be plotted with the highest color.
#' @param clear_artifacts logical. It is a known and documented issue that the 3D visualisation with
#' \code{rgl} displays artifacts. The points look aligned and/or regularly spaced in some view angles.
#' This is because \code{rgl} computes with single precision \code{float}. To fix that the point
#' cloud is shifted to (0,0) to reduce the number of digits needed to represent its coordinates.
#' The drawback is that the point cloud is not plotted at its actual coordinates.
#' @param nbits integer. If \code{color = RGB} it assumes that RGB colors are coded on 16 bits as described
#' in the LAS format specification. However, this is not always respected. If the colors are stored
#' on 8 bits set this parameter to 8.
#' @param axis logical. Display axis on XYZ coordinates.
#' @param legend logical. Display a gradient color legend.
#' @param backend character. Can be \code{"rgl"} or \code{"pcv"}. If \code{"rgl"} is chosen
#' the display relies on the \code{rgl} package. If \code{"pcv"} is chosen it relies on the
#' \code{PointCloudViewer} package, which is much more efficient and can handle million of points
#' using less memory. \code{PointCloudViewer} is not available on CRAN yet and should
#' be installed from github (see. \url{https://github.com/Jean-Romain/PointCloudViewer}).
#' @param ... Will be passed to \link[rgl:points3d]{points3d} (LAS) or \link[graphics:plot]{plot}
#' if \code{mapview = FALSE} or to \link[mapview:mapView]{mapview} if \code{mapview = TRUE} (LAScatalog).
#' @examples
#' LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
#' las <- readLAS(LASfile)
#'
#' plot(las, clear_artifact = TRUE)
#'
#' # Outliers in intensity break the color range. Use the trim parameter.
#' col <- heat.colors(50)
#' plot(las, color = Intensity, colorPalette = col)
#' plot(las, color = Intensity, colorPalette = col, trim = 70)
#' @export
#' @method plot LAS
setGeneric("plot", function(x, y, ...)
  standardGeneric("plot"))

#' Test if a \code{LAS} object is empty
#'
#' An empty \code{LAS} object is a point cloud with 0 points
#'
#' @param object A \code{LAS} object
#' @param ... Unused
#'
#' @return TRUE or FALSE
#'
#' @examples
#' LASfile <- system.file("extdata", "example.laz", package="rlas")
#' las = readLAS(LASfile)
#' is.empty(las)
#'
#' las = new("LAS")
#' is.empty(las)
#' @export
setGeneric("is.empty", function(object, ...)
  standardGeneric("is.empty"))

#' Surface covered by a LAS* object.
#'
#' Surface covered by a \code{LAS*} object. For \code{LAS} point clouds it is computed based on the
#' convex hull of the points. For a \code{LAScatalog} it is computed as the sum of the bounding boxes
#' of the files. For overlapping tiles the value may be larger than the total covered area because
#' some regions are sampled twice.
#'
#' @param x An object of the class \code{LAS*}
#' @param ... unused
#'
#' @return numeric. The area of the object computed in the same units as the coordinate reference system
#' @export
#' @importMethodsFrom raster area
#' @rdname area
setGeneric("area", function(x, ...)
  standardGeneric("area"))

#' Get or set the projection of a LAS* object
#'
#' Get or set the projection of a LAS* object with the function \code{projection}. Fonctions \code{epsg}
#' and \code{wkt} are reserved to advanced users (see details).
#'
#' There are two ways to store the CRS of a point cloud in a las file:
#' \itemize{
#' \item Store an EPSG code (for LAS 1.0 to 1.4)
#' \item Store a WTK string (for LAS 1.4)
#' }
#' On the other hand, all spatial R packages use a \code{proj4string} to store the CRS. This is why
#' the CRS is duplicated in a LAS object. The information belongs within the header in a format that
#' can be written in a LAS file and in the slot \code{proj4string} in a format that can be understood
#' by R packages.
#' \itemize{
#' \item \code{projection<-}: updates the CRS from a \code{proj4string} It updates the header either
#' with the EPSG code for LAS formats < 1.4 or with a WKT string for LAS format 1.4 and updates the
#' \code{proj4string} slot. This function should always be prefered.
#' \item \code{epsg<-}: updates the CRS from an EPSG code. It adds the epsg code in the header and updates
#' the \code{proj4string} slot
#' \item \code{wkt<-}: updates the CRS from a WKT string. It adds the WKT string in the header and updates
#' the \code{proj4string} slot
#' \item \code{projection}: reads the \code{proj4string} from the \code{proj4string} slot.
#' \item \code{epsg}: reads the epsg code from the header.
#' \item \code{wkt}: reads the WKT string from the header.
#' }
#'
#' @param object,x An object of class LAS or eventually LASheader (regular users don't need to manipulate
#' LASheader objects)
#' @param ... Unused
#' @param asText logical. If TRUE, the projection is returned as text. Otherwise a CRS object is returned
#' @param value A \code{CRS} object or a \code{proj4string} string for function\code{projection}.
#' An EPSG code as integer for function \code{epsg}. A \code{WKT} string for function \code{wkt}.
#'
#' @export
#' @examples
#' LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
#' las <- readLAS(LASfile)
#' crs <- sp::CRS("+init=epsg:26918")
#'
#' projection(las)
#' projection(las) <- crs
#' @importFrom raster projection<-
#' @importFrom raster projection
#' @name projection
#' @rdname projection
NULL

#' @export
#' @rdname projection
setGeneric("epsg", function(object, ...)
  standardGeneric("epsg"))

#' @export
#' @rdname projection
setGeneric("epsg<-", function(object, value)
  standardGeneric("epsg<-"))

#' @export
#' @rdname projection
setGeneric("wkt", function(object, ...)
  standardGeneric("wkt"))

#' @export
#' @rdname projection
setGeneric("wkt<-", function(object, value)
  standardGeneric("wkt<-"))
