# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_table <- function(x, size = 5L) {
    .Call(`_lidR_fast_table`, x, size)
}

fast_countequal <- function(x, t) {
    .Call(`_lidR_fast_countequal`, x, t)
}

fast_countbelow <- function(x, t) {
    .Call(`_lidR_fast_countbelow`, x, t)
}

fast_countover <- function(x, t) {
    .Call(`_lidR_fast_countover`, x, t)
}

roundc <- function(x, digit = 0L) {
    .Call(`_lidR_roundc`, x, digit)
}

C_dalponte2016 <- function(Image, Seeds, th_seed, th_crown, th_tree, DIST) {
    .Call(`_lidR_C_dalponte2016`, Image, Seeds, th_seed, th_crown, th_tree, DIST)
}

C_knn <- function(X, Y, x, y, k) {
    .Call(`_lidR_C_knn`, X, Y, x, y, k)
}

C_knnidw <- function(X, Y, Z, x, y, k, p) {
    .Call(`_lidR_C_knnidw`, X, Y, Z, x, y, k, p)
}

C_lassmooth <- function(las, size, method = 1L, shape = 1L, sigma = 1) {
    .Call(`_lidR_C_lassmooth`, las, size, method, shape, sigma)
}

C_li2012 <- function(las, dt1, dt2, Zu, R, th_tree, radius) {
    .Call(`_lidR_C_li2012`, las, dt1, dt2, Zu, R, th_tree, radius)
}

C_lmf <- function(data, ws, min_height, circular) {
    .Call(`_lidR_C_lmf`, data, ws, min_height, circular)
}

C_MorphologicalOpening <- function(X, Y, Z, resolution) {
    .Call(`_lidR_C_MorphologicalOpening`, X, Y, Z, resolution)
}

R_p2r <- function(las, bbox, res, subcircle = 0) {
    .Call(`_lidR_R_p2r`, las, bbox, res, subcircle)
}

C_point_in_polygon <- function(vertx, verty, pointx, pointy) {
    .Call(`_lidR_C_point_in_polygon`, vertx, verty, pointx, pointy)
}

C_points_in_polygon <- function(vertx, verty, pointx, pointy) {
    .Call(`_lidR_C_points_in_polygon`, vertx, verty, pointx, pointy)
}

C_points_in_polygon_wkt <- function(x, y, wkt) {
    .Call(`_lidR_C_points_in_polygon_wkt`, x, y, wkt)
}

C_circle_lookup <- function(X, Y, x, y, r) {
    .Call(`_lidR_C_circle_lookup`, X, Y, x, y, r)
}

C_knn3d_lookup <- function(X, Y, Z, x, y, z, k) {
    .Call(`_lidR_C_knn3d_lookup`, X, Y, Z, x, y, z, k)
}

C_tinfo <- function(M, X) {
    .Call(`_lidR_C_tinfo`, M, X)
}

C_tsearch <- function(x, y, elem, xi, yi) {
    .Call(`_lidR_C_tsearch`, x, y, elem, xi, yi)
}

C_Wing2015 <- function(las, neigh_radii, low_int_thrsh, uppr_int_thrsh, pt_den_req, BBPRthrsh_mat) {
    .Call(`_lidR_C_Wing2015`, las, neigh_radii, low_int_thrsh, uppr_int_thrsh, pt_den_req, BBPRthrsh_mat)
}

