# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Do point fall in a given polygon?
#'
#' Verifies for one point whether it fall in a given polygon
#'
#' @param vertx  numerical array of x-coordinates of polygon
#' @param verty  numerical array of y-coordinates of polygon
#' @param pointx numeric. x-coordinate of a point
#' @param pointy numeric. y-coordinate of a point
#' @return Logical. FALSE, point is exterior to the polygon, TRUE, point is in interior to the polygon
#' @references Adaptation of the C function written by W. Randolph Franklin
#' @export
point_in_polygon <- function(vertx, verty, pointx, pointy) {
    .Call('lidR_point_in_polygon', PACKAGE = 'lidR', vertx, verty, pointx, pointy)
}

#' Do points fall in a given polygon?
#'
#' Verifies for a set of points whether they fall in a given polygon
#'
#' @param vertx  numerical array of x-coordinates of polygon
#' @param verty  numerical array of y-coordinates of polygon
#' @param pointx numerical array of x-coordinates of points
#' @param pointy numerical array of y-coordinates of points
#' @return Logical array. FALSE, point is exterior to the polygon, TRUE, point is in interior to the polygon
#' @export
points_in_polygon <- function(vertx, verty, pointx, pointy) {
    .Call('lidR_points_in_polygon', PACKAGE = 'lidR', vertx, verty, pointx, pointy)
}

#' Do points fall in a one of the polygons?
#'
#' Verifies for a set of points whether they fall in one of the given polygon
#'
#' @param vertx  numerical list of array of x-coordinates of polygon
#' @param verty  numerical list of array of y-coordinates of polygon
#' @param pointx numerical array of x-coordinates of points
#' @param pointy numerical array of y-coordinates of points
#' @return numerical array. 0 if the points are in any polygon or the number of the polygon if points fall in a polygon
#' @export
points_in_polygons <- function(vertx, verty, pointx, pointy) {
    .Call('lidR_points_in_polygons', PACKAGE = 'lidR', vertx, verty, pointx, pointy)
}

readLASdata <- function(file, Intensity = TRUE, ReturnNumber = TRUE, NumberOfReturns = TRUE, ScanDirectionFlag = FALSE, EdgeofFlightline = FALSE, Classification = TRUE, ScanAngle = TRUE, UserData = FALSE, PointSourceID = FALSE, RGB = TRUE) {
    .Call('lidR_readLASdata', PACKAGE = 'lidR', file, Intensity, ReturnNumber, NumberOfReturns, ScanDirectionFlag, EdgeofFlightline, Classification, ScanAngle, UserData, PointSourceID, RGB)
}

readLASheader <- function(file) {
    .Call('lidR_readLASheader', PACKAGE = 'lidR', file)
}

LASlibWrite <- function(file, LASheader, X, Y, Z, I = integer(0), RN = integer(0), NoR = integer(0), SDF = integer(0), EoF = integer(0), C = integer(0), SA = integer(0), UD = integer(0), PSI = integer(0), T = numeric(0), R = integer(0), G = integer(0), B = integer(0)) {
    invisible(.Call('lidR_LASlibWrite', PACKAGE = 'lidR', file, LASheader, X, Y, Z, I, RN, NoR, SDF, EoF, C, SA, UD, PSI, T, R, G, B))
}

